Allanleal cpp reactivetransportsolver demo
reaktoro/reaktoro pull request #159
Opened 2020-09-21 10:06 UTC by mtsveta

Fixes of the SmartEquilibrium method: 
1) Storing of the chemical state returned by the conventional solver that didn't have good convergence
2) Relacing negative values by the small epsilon value in the estimate() method 
3) Adding scaling in the ReactiveTransportSolver

More changes in demos are added.

2020-11-20 08:22 UTC, allanleal requested changes
This is excellent work. I have reviewed up to the `SmartEquilibriumSolver`. Let's implement it using the functional programming style I described there instead of using inheritance and pure virtual methods. The functional style will let us concentrate on a single class whose object can be customized in a variety of ways, avoiding with this the explosion of derived classes to handle each combination of possibilities.

2020-11-20 08:22 UTC, allanleal commented on Reaktoro/Equilibrium/SmartEquilibriumSolverBase.hpp
> +    virtual auto learn(ChemicalState& state, double T, double P, VectorConstRef be) -> void = 0;
Best to avoid inheritance at all costs. In Reaktoro, runtime polymorphism is in most cases done in a functional programming style where functions are considered data members. See code below:

~~~cpp
class SmartEquilibriumSolver
{
public:
    /// The state of the smart equilibrium solver.
    struct SolverState
    {
        // put here things that the functions
        // below need to access and change, possibly
        // including ChemicalState, temperature, pressure
        // b vector
    };

    /// The functional signature of functions that perform learning operations.
    using LearnFn = std::function<void(SolverState& solverstate)>;

    /// The functional signature of functions that perform prediction operations.
    using EstimateFn = std::function<void(SolverState& solverstate)>;

    /// Set the function that performs the learning operation.
    auto setLearnFn(const LearnFn& learnfn) -> void;

    /// Set the function that performs the prediction operation.
    auto setEstimateFn(const LearnFn& learnfn) -> void;

    /// Solve the chemical equilibrium problem.
    auto solve(ChemicalState& state, const EquilibriumProblem& problem) -> SmartEquilibriumResult;

private:
    /// The function that perform the learning operation.
    LearnFn learnfn;

    /// The function that perform the prediction operation.
    EstimateFn estimatefn;
};
~~~

This will eliminate all the derived classes you had to implement. We will only have one class: `SmartEquilibriumSolver`. We can define the learn and estimate functions using lambda functions and set them to `SmartEquilibriumSolver`. 

Say you have a function that returns a lambda function (in functional programming, this function is called a *higher-order function*) for the estimate step based on nearest neighbor: 

~~~cpp
auto createEstimateFnBasedOnNearestNeighborSearch() -> SmartEquilibriumSolver::EstimateFn;
~~~

we can then do:

~~~cpp
SmartEquilibriumSolver smartsolver(system);

smartsolver.setEstimateFn(createEstimateFnBasedOnNearestNeighborSearch());
~~~

We should, however, have already some set methods in the `SmartEquilibriumSolver` to simplify this:

~~~cpp

class SmartEquilibriumSolver
{
public:
    /// The state of the smart equilibrium solver.
    struct SolverState
    {
        // put here things that the functions
        // below need to access and change, possibly
        // including ChemicalState, temperature, pressure
        // b vector
    };

    /// The functional signature of functions that perform learning operations.
    using LearnFn = std::function<SolverState& solverstate>;

    /// The functional signature of functions that perform prediction operations.
    using EstimateFn = std::function<SolverState& solverstate>;

    /// Set the function that performs the learning operation.
    auto setLearnFn(const LearnFn& learnfn) -> void;

    /// Set the function that performs the prediction operation.
    auto setEstimateFn(const LearnFn& learnfn) -> void;

    /// Specify smart predictions to be done using nearest neighbor search.
    auto useNearestNeighborSearch() -> void;

    /// Specify smart predictions to be done using priority-queue search.
    auto usePriorityQueueSearch() -> void;

    /// Specify smart predictions to be done using clusterized priority-queue search.
    auto useClusterizedPriorityQueueSearch() -> void;
    
    //  more methods here to specify how the learning is done.
    
    /// Solve the chemical equilibrium problem.
    auto solve(ChemicalState& state, const EquilibriumProblem& problem) -> SmartEquilibriumResult;

private:
    ///< The function that perform the learning operation.
    LearnFn learnfn;

    ///< The function that perform the prediction operation.
    EstimateFn estimatefn;
};
~~~

2020-11-20 11:32 UTC, allanleal commented on Reaktoro/Equilibrium/SmartEquilibriumSolverBase.hpp
> +    virtual auto learn(ChemicalState& state, double T, double P, VectorConstRef be) -> void = 0;
After a video call, we decided to take advantage of this already implemented code but have a `SmartEquilibriumSolver` class that encapsulates a pointer to `SmartEquilibriumSolverBase` and provides mechanisms to choose which algorithm to be used! :+1:

2020-11-20 14:18 UTC, volpatto commented on Reaktoro/Equilibrium/SmartEquilibriumSolverBase.cpp
> +        : system(system), partition(Partition(system)),
Ahh, indeed, @allanleal. I have one `.clag-format` here for `reaktoro`. My bad, it was defined in a PR that is still open, I think it's time to finish what I was doing there, since it could solve "style reviews" and help to focus on other things in the PRs. Should I attach `.clang-format` here or it's better to open a quick PR and then @mtsveta can sync with master after the merge?

2020-11-20 15:24 UTC, allanleal commented
Hi Diego, let's not do this now. We can setup this for the v2.0.

>

2020-11-27 08:17 UTC, allanleal reviewed
Hi Svetlana, this is great! Just a few things to address now. We should eventually have a repo for the mode complicated/long demos. At this point, I think it is fine to have them in the main repo.

2020-11-27 08:17 UTC, allanleal commented on Reaktoro/Kinetics/KineticOptions.hpp
> +    bool use_smart_equilibrium_solver = false;
It's good this is `false` by default. I think the input conditions given to the equilibrium solver during kinetics integration can be erratic and the `SmartEquilibriumSolver` could be populated with lots of trained calculations that are actually not useful.

2020-11-27 08:17 UTC, allanleal commented on demos/cpp/TestUtils.h
> +// Reaktoro is a unified framework for modeling chemically reactive systems.
Let's call this `Utils.hpp` or `DemosUtils.hpp`.

2020-11-27 08:17 UTC, allanleal commented on demos/python/demo-equilibrium-sechenov-activity-model.py
> +from reaktoro import *
demo-equilibrium-setschenow-activity-model.py

2021-01-21 08:59 UTC, merged