[WIP] Separate CubicEOS Python bindings in a proper file and expose BIPs
reaktoro/reaktoro pull request #177
Opened 2021-01-29 20:15 UTC by volpatto

2021-01-29 20:57 UTC, allanleal commented on python/PyReaktoro/Thermodynamics/Models/PyCubicEos.cpp
> +// Reaktoro is a unified framework for modeling chemically reactive systems.
`CubicEos` -> `CubicEOS`

2021-01-29 20:57 UTC, allanleal commented on python/PyReaktoro/Thermodynamics/Models/PyCubicEos.cpp
> +}
Are you going to create bindings for `CubicEOSInteractionParamsArgs` and `CubicEOS::setInteractionParamsFunction` in this PR? I this what you needed?

2021-01-29 21:04 UTC, volpatto commented on python/PyReaktoro/Thermodynamics/Models/PyCubicEos.cpp
> +// Reaktoro is a unified framework for modeling chemically reactive systems.
Whoops, thanks!

2021-01-29 21:05 UTC, volpatto commented on python/PyReaktoro/Thermodynamics/Models/PyCubicEos.cpp
> +}
Yes, we need to set such values for Cubic EOS models.

2021-01-29 21:10 UTC, volpatto commented on python/PyReaktoro/Thermodynamics/Models/PyCubicEos.cpp
> +// Reaktoro is a unified framework for modeling chemically reactive systems.
Fixed now, I think.

2021-02-02 01:02 UTC, volpatto commented on Reaktoro/Thermodynamics/EOS/CubicEOS.cpp
> -        InteractionParamsArgs kargs{T, a, aT, aTT, b};
I think the common arg for BIPs is the temperature only. Most of the time BIPs have constant value or given as a polynomial, so I removed those other args.

2021-02-02 01:06 UTC, volpatto commented on Reaktoro/Thermodynamics/EOS/CubicEOS.cpp
> +                const double rTT = kres.kTT.size() ? -kres.kTT(i, j) : 0.0;
I have had to change this part since the bindings are straightforward using Eigen. The logic is the same. If a `MatrixXd` is just declared, the `size` would be `col * rows`, with `col = rows = 0`. This `k.size() = 0` if the BIPs are not defined.

2021-02-02 01:07 UTC, volpatto commented on Reaktoro/Thermodynamics/EOS/CubicEOS.hpp
> +        MatrixXd k;
Despite the name, those `MatrixXd`s are aliases defined in `Reaktoro/Math/Matrix.hpp`.

2021-02-02 01:11 UTC, volpatto commented on python/PyReaktoro/Thermodynamics/Models/PyCubicEOS.cpp
> +            py::arg("kTT") = MatrixXd{}
I did this because it allows the user to define only `k` without defining `kT` and `kTT`. This is useful since most of the time `k` has constant entries. I don't think it has any side effect due to those [ternary operators](https://github.com/reaktoro/reaktoro/pull/177/files#r568251361).

2021-02-02 01:14 UTC, volpatto commented on python/PyReaktoro/Thermodynamics/Models/PyCubicEOS.cpp
> +            py::arg("kTT") = MatrixXd{}
Btw, it is not a Ref MatrixXd. The reason is that if the user passes a `List` in Python (as in the tests below), it would raise an error due to type incompatibility.

2021-02-02 01:19 UTC, volpatto commented
No tests are provided to check the effect of BIPs on Equilibrium calculations in this PR. I'm planning to do it as soon as we merge this PR. I'm working on Hydrocarbon mixtures using Cubic EOS in [this branch](https://github.com/volpatto/reaktoro/tree/add-hydrocarbon-tests).

2021-02-02 13:53 UTC, tadeu requested changes
Nice improvement!

2021-02-02 13:53 UTC, tadeu commented on tests/test_cubiceos.py
> +    assert np.allclose(bips_calculated.k, bips_expected.k)
Could check for equality here, also checking that `kT` and `kTT` are zero

2021-02-02 13:55 UTC, tadeu commented on tests/test_cubiceos.py
> +import numpy as np
About the file name, are we using the casing like `test_cubiceos.py` or like `test_CubicEOS.py`?

2021-02-02 16:56 UTC, volpatto commented on Reaktoro/Thermodynamics/EOS/CubicEOS.cpp
> +                const double rTT = kres.kTT.size() ? -kres.kTT(i, j) : 0.0;
I think it would be interesting to have a "size check" for those BIPs matrix. I mean, suppose we have `n` species. So all BIPs matrices have dimension `(n, n)`. I need to elaborate it further in the code.

2021-02-02 16:57 UTC, volpatto commented on tests/test_cubiceos.py
> +    assert np.allclose(bips.k, k)
Thanks! I will improve it as suggested

2021-02-02 16:58 UTC, volpatto commented on tests/test_cubiceos.py
> +import numpy as np
This is a good question. I would prefer `test_CubicEOS.py`.

2021-02-02 17:11 UTC, tadeu commented on tests/test_cubiceos.py
> +import numpy as np
Just checked here, for consistency it should be lowercase (as it already is), I think that they were all renamed at some point :)

2021-02-02 18:52 UTC, volpatto commented on Reaktoro/Thermodynamics/EOS/CubicEOS.cpp
> +auto CubicEOS::sanityCheckInteractionParamsFunction(const InteractionParamsFunction& func) -> void
I added this function to check if BIPs have the right dimensions.

2021-02-02 18:54 UTC, volpatto commented on Reaktoro/Thermodynamics/EOS/CubicEOS.cpp
> +        sanityCheckInteractionParamsFunction(params.binary_interaction_values);
Now we have a sanity check for BIPs. Please [see here](https://github.com/reaktoro/reaktoro/pull/177/files#r568849826).

2021-02-02 18:55 UTC, volpatto commented on Reaktoro/Thermodynamics/EOS/CubicEOS.cpp
> +                const double rTT = kres.kTT.size() ? -kres.kTT(i, j) : 0.0;
> I think it would be interesting to have a "size check" for those BIPs matrix. I mean, suppose we have `n` species. So all BIPs matrices have dimension `(n, n)`. I need to elaborate it further in the code.

Implemented [here](https://github.com/reaktoro/reaktoro/pull/177/files#r568849826).

2021-02-02 20:38 UTC, volpatto commented on Reaktoro/Thermodynamics/Core/Database.cpp
> +            }
This modification was necessary to properly read hydrocarbon data from the custom xml database.

2021-02-02 20:40 UTC, volpatto commented on tests/data/hydrocarbons.xml
> +<?xml version="1.0" ?>
A custom Database containing Hydrocarbon data to be used in Liquid phases. This is only for the tests.

2021-02-02 20:54 UTC, volpatto commented
> This PR contains the following changes:
> 
> * [x]  Move `CubicEOS::Params` definitions and bindings inside `PyFluidPhase` to a proper file `PyCubicEos`;
> * [x]  Expose setup Binary Interaction Parameters through Cubic EOS Python bindings;
> * [x]  Tests in Python for the exposed features. Please see `tests/test_cubiceos.py`;
> * [x]  Fix Database parser for `Liquid` type species;
> * [x]  Add a custom xml database for hydrocarbons components. Only for tests purpose.

The PR is now tackling an increased number of issues. Should I rename the PR? Any suggestions?
I'm planning to add a hydrocarbon case using non-zero BIPs and stop at this point.

2021-02-02 21:38 UTC, allanleal commented on Reaktoro/Thermodynamics/EOS/CubicEOS.cpp
> +                const double r = kres.k.size() ? 1.0 - kres.k(i, j) : 1.0;
If `k` has any dependency on temperature, this change here (using `double`) will prevent temperature derivatives.

2021-02-02 21:38 UTC, allanleal commented on Reaktoro/Thermodynamics/EOS/CubicEOS.hpp
> +        std::function<InteractionParamsResult(const double&)>;
The argument here should be `const ThermoScalar&` (instead of `const double&`) which will be temperature. Otherwise, we are not able to compute temperature derivatives. Even for `kTT`, we are able to get `kTT.ddT` (with automatic differentiation).

2021-02-02 21:38 UTC, allanleal commented on Reaktoro/Thermodynamics/EOS/CubicEOS.hpp
> +    auto sanityCheckInteractionParamsFunction(const InteractionParamsFunction& func) -> void;
This method declaration should not be exposed here - move it to `CubicEOS.cpp` (possibly as a free function), where it is used.

2021-02-02 21:38 UTC, allanleal commented on Reaktoro/Thermodynamics/EOS/CubicEOS.hpp
> +        MatrixXd k;
This will become `MatrixXr` in the v2.0 (matrix of `real` numbers, where `real` is an `autodiff` type)

2021-02-03 14:29 UTC, tadeu commented on tests/test_cubiceos.py
> +    assert bips.k.all() == np.array(k).all()
Should be:

```
assert np.all(bips.k == k)
```

or, for better error messages:

```
assert_array_equal(bips.k, k)
```

2021-02-15 19:57 UTC, volpatto commented on Reaktoro/Thermodynamics/EOS/CubicEOS.hpp
> +        std::function<InteractionParamsResult(const double&)>;
Hmm.. I see! Well, it means that we should have `ThermoScalar` with Python bindings. I looked for it and I have not found it, maybe I'm missing something. Do you have any advice? `ThermoScalar` is pretty big, so it would demand some time to expose.

2021-02-15 19:58 UTC, volpatto commented on Reaktoro/Thermodynamics/EOS/CubicEOS.hpp
> +    auto sanityCheckInteractionParamsFunction(const InteractionParamsFunction& func) -> void;
Sure, thanks

2021-02-15 20:33 UTC, volpatto commented on Reaktoro/Thermodynamics/EOS/CubicEOS.hpp
> +    auto sanityCheckInteractionParamsFunction(const InteractionParamsFunction& func) -> void;
Done.

2021-02-15 21:23 UTC, volpatto commented on Reaktoro/Thermodynamics/EOS/CubicEOS.hpp
> +        std::function<InteractionParamsResult(const double&)>;
Sorry, nevermind. Found everything I need in `PyAutoDiff.cpp`.

2021-02-16 13:23 UTC, volpatto commented on Reaktoro/Thermodynamics/EOS/CubicEOS.cpp
> +                const double r = kres.k.size() ? 1.0 - kres.k(i, j) : 1.0;
Done. I wonder if this is the better approach. What do you think about the code below?
```c++
const ThermoScalar r = kres.k.size() ? ThermoScalar(1.0 - kres.k(i, j)) : ThermoScalar(1.0);
```

I'm asking because I have changed the BIPs input using `ThermoScalar`, but with Eigen things are far simpler, IMHO.

2021-02-16 13:24 UTC, volpatto commented on Reaktoro/Thermodynamics/EOS/CubicEOS.hpp
> +        std::function<InteractionParamsResult(const double&)>;
Done.

2021-02-16 13:26 UTC, volpatto commented on docs/sphinx/acknowledgements.rst
> +* Diego T. Volpatto *(ESSS, Brazil)* *(2020-present)*
I updated the acknowledgements. Please correct me if something is wrong.

2021-02-16 13:34 UTC, allanleal commented on Reaktoro/Thermodynamics/EOS/CubicEOS.cpp
> +                const double r = kres.k.size() ? 1.0 - kres.k(i, j) : 1.0;
This is fine. It could also be:

~~~cpp
const auto r = kres.k.size() ? 1.0 - kres.k(i, j) : ThermoScalar(1.0);
~~~

The `ThermoScalar(1.0)` is needed otherwise you have a ternary operator that has two different return types (`ThermoScalar` from the `1 - kij` branch, and `double` from the `1.0` branch). 

This is simpler with `autodiff::real` in the v2.0.

2021-02-16 13:35 UTC, allanleal commented on docs/sphinx/acknowledgements.rst
> +* Diego T. Volpatto *(ESSS, Brazil)* *(2020-present)*
Looks good.

2021-02-16 13:36 UTC, volpatto commented on tests/test_cubiceos.py
>      bips = BinaryInteractionParams(k, kT, kTT)
@allanleal I don't know if this is according to your expectations, but I set the BIPs to use `ThermoScalar` in the input. IMHO, the complexity drastically increased, but maybe this is the price to enable automatic differentiation. Please note below that now we can't handle BIPs matrices in Python directly as `List`s or `numpy.ndarray`s without a post-processing for-loop, just like the `assert`s in the final of this test.

Is it OK? Are we good to go?

2021-02-16 13:41 UTC, volpatto commented on Reaktoro/Thermodynamics/EOS/CubicEOS.cpp
> +                const double r = kres.k.size() ? 1.0 - kres.k(i, j) : 1.0;
But what about the automatic differentiation? Some BIPs can depend on temperature... I'm trying to find a solution that keeps the simplicity of `Eigen::MatrixXd` as interface with the `ThermoScalar` auto diff capabilities.

2021-02-16 13:43 UTC, allanleal commented on Reaktoro/Thermodynamics/Core/Database.cpp
> +            }
Can we use `(l)` here without breaking other codes? This would be more preferable.

2021-02-16 13:43 UTC, volpatto commented on tests/test_cubiceos.py
>      bips = BinaryInteractionParams(k, kT, kTT)
The ideal solution, IMHO, would be the implementation of `ThermoMatrix` based on `ThermoVector`. It was a little bit cumbersome to write each BIPs matrix input as `ThermoScalar`, but I think we can go with that as well.

2021-02-16 13:44 UTC, volpatto commented on tests/test_cubiceos.py
>      bips = BinaryInteractionParams(k, kT, kTT)
> The ideal solution, IMHO, would be the implementation of `ThermoMatrix` based on `ThermoVector`. It was a little bit cumbersome to write each BIPs matrix input as `ThermoScalar`, but I think we can go with that as well.

However, this would result in a considerable amount of work for me haha

2021-02-16 13:48 UTC, volpatto commented on Reaktoro/Thermodynamics/Core/Database.cpp
> +            }
Sure, we could define "Reaktoro's standard". I think we need to inform the user about "custom databases" somewhere, but no idea where. Any recommendation in this regard?

2021-02-16 13:59 UTC, allanleal commented on tests/test_cubiceos.py
>      bips = BinaryInteractionParams(k, kT, kTT)
I'm getting rid of all these ThermoScalar, ThermoVector, ChemicalScalar, ChemicalVector in the v2.0 - we can have Eigen Matrix of autodiff::real there and this is what you want (but it's not worth doing similar things here, implementing a ThermoMatrix).

2021-02-16 14:28 UTC, allanleal approved these changes
Perfect! Thanks @volpatto .

2021-02-16 14:29 UTC, merged