Add tests and improvements for equilibrium considering hydrocarbons
reaktoro/reaktoro pull request #203
Opened 2021-07-07 18:08 UTC by alexandrebbruno

Add tests with hydrocarbons with code improvements

authored-by: Diego Volpatto <volpatto@lncc.br>
Co-authored-by: Alexandre B. Bruno <alexandrebbruno@gmail.com>

2021-07-07 18:14 UTC, volpatto commented
@allanleal this is the work I have done in the beginning of this year for Hydrocarbon mixtures. Unfortunately, I ran out of time and then @alexandrebbruno rescued this work (thanks a lot!) and made some improvements.

Note that the calculations inside `CubicEOS` are slightly different right now, and potentially can effect every mixture that uses this thermodynamic model.

This work is split in more than one PR. More PRs can be open in the future and there are rooms for improvements.

2021-07-07 18:49 UTC, allanleal requested changes
Thanks @volpatto and @alexandrebbruno . Please have a look at my comments and suggestions.

2021-07-07 18:49 UTC, allanleal commented on Reaktoro/Core/ChemicalProperties.cpp
> +auto ChemicalProperties::phaseCompressibilityFactors() const -> ChemicalVector
This class (named `ChemicalProps` in v2.0) should contain only those more fundamental thermodynamic properties. Better to transform this into a non-member function in `Thermodynamics/Utils.hpp`: 

~~~c++
auto phaseCompressibilityFactors(const ChemicalProperties&) -> ChemicalVector;
~~~

2021-07-07 18:49 UTC, allanleal commented on tests/regression/test_equilibrium_liq_gas.py
> +    options.optimum.max_iterations = 2000
If the solver did not converge up to 200, then chances are that it won't for 2000! ;)

2021-07-07 18:49 UTC, allanleal commented on tests/regression/test_pedersen63.py
> +import numpy as np
I'm concerned with the length of this test and its future maintainability. It even has plots. This should perhaps be broken down into a tutorial/example script and a regression test. We should aim for simpler tests so that we don't have to spend a lot of time on it in the future if it breaks.

2021-07-07 18:49 UTC, allanleal commented on tests/regression/test_whitson18.py
> +import numpy as np
Same argument here about aiming for simpler and more straightforward tests.

2021-07-07 19:08 UTC, volpatto commented on tests/regression/test_pedersen63.py
> +import numpy as np
Yes, indeed, the test is very long, I understand your point and I would like to share my opinion in some points.

The tutorial is a great idea, we can write one.

The idea and purpose of this test is to aim at "validation" and it is more like an integration test. The Reaktoro results are compared with results from well established literature. It has some "regressions", but regressions are not aimed to "validate", just to verify if a behavior is consistent through changes, even if the behavior is, well, wrong (when the regression test was inappropriately designed), i.e., regressions compare Reaktoro with itself. The idea of this test is different, it is to assert that Reaktoro result is valid against references.

In this sense, I think we could break this test in more tests, one for regressions, other for validation/verification.

The part of "plotting" can be removed, it is there just to check visually if a flag is set.

In my opinion, tests like this one is important and welcome, because it adds confidence to Reaktoro. But we can simplify and even remove the comparisons, turn it to simple regression tests as you suggested, no problem.

2021-07-07 19:23 UTC, volpatto reviewed
Thanks for your review, @allanleal. I have added some comments to help our improvements/corrections.

2021-07-07 19:23 UTC, volpatto commented on tests/regression/test_pedersen63.py
> +    df_pvtlib_composition_liq.reset_index(drop=True, inplace=True)
To simplify the test, I think that we could encapsulate parts like this one in fixtures.

2021-07-07 19:23 UTC, volpatto commented on tests/regression/test_pedersen63.py
> +        plt.show()
I think that we could remove plots like this one, and put them in a tutorial. I think it would be good to create a ipynb and add it to `reaktoro-jupyter` repo. I could do it.

2021-07-07 19:25 UTC, allanleal commented on tests/regression/test_pedersen63.py
> +    df_pvtlib_composition_liq.reset_index(drop=True, inplace=True)
I think the fixture would make more sense if this becomes used all over the place, but I don't think it's the case. Let me know.

2021-07-07 19:29 UTC, volpatto commented on tests/regression/test_pedersen63.py
> +    df_pvtlib_composition_liq.reset_index(drop=True, inplace=True)
Indeed, it is just a unique use. I was think to put it in a fixture to make the test at least clearer and smaller. This part will never break as soon as `pandas` does not break. It is just a "data gathering" step.

2021-07-07 20:55 UTC, allanleal commented on tests/regression/test_pedersen63.py
> +import numpy as np
Absolutely. We should have validation tests (like this one) as well (in addition to regression). 

The idea of shorter and more straightforward tests is to safeguard whoever is developing/contributing to Reaktoro (or its dependencies) and then needs to fix broken regression tests as a result of some code changes. But I understand sometimes simple enough is the way to go.

2021-07-07 20:58 UTC, volpatto commented on tests/regression/test_pedersen63.py
> +import numpy as np
Yeah, I agree.

I will see with the guys how we can improve the tests and simplify them.

2021-07-07 21:00 UTC, allanleal commented on tests/regression/test_pedersen63.py
> +    df_pvtlib_composition_liq.reset_index(drop=True, inplace=True)
Better to keep these parts together then. We need to have tests structured/defined in a very intuitive way (so that everyone should be able to fix them quickly in case they break in the future). Moving parts to different locations will make them more difficult to understand. If a computed object needs to be used by many tests and its computation is time-consuming, then we move this to a single location (fixture).

2021-07-09 20:54 UTC, alexandrebbruno commented on Reaktoro/Core/ChemicalProperties.cpp
> +auto ChemicalProperties::phaseCompressibilityFactors() const -> ChemicalVector
Done,
move this function to Thermodynamics/ThermodynamicsUtils.hpp:

2021-07-09 20:56 UTC, alexandrebbruno commented on tests/regression/test_equilibrium_liq_gas.py
> +    options.optimum.max_iterations = 2000
yep! I changed back to 200 and the test converged

2021-07-09 21:03 UTC, alexandrebbruno commented on tests/regression/test_pedersen63.py
> +import numpy as np
Hey guys,

I think I've found a nice solution for both tests.
Solution:
- diego will make a demo demo for reaktoro-jupyter with the plot that I've removed from the test
- also tried to make those tests simpler and more straight foward

If you guys are still thinking that the test is complicated, I can try to remove the comparison with the pvtlib and only do the validation using regression

2021-07-12 09:25 UTC, allanleal commented
Hi @alexandrebbruno - many thanks for revising this PR. All is fine now. Please see however my point about not considering the `phaseCompressibilityFactors` function in this PR.

2021-07-12 09:25 UTC, allanleal commented on Reaktoro/Thermodynamics/ThermodynamicsUtils.cpp
> +auto phaseCompressibilityFactors(const ChemicalProperties& properties) -> ChemicalVector
This file should be `Thermodynamics/Utils.hpp/cpp`. Repeated file names are OK, as long as they are in different directories. I'm now wondering however why we need this function. It is a simple computation and also specific to systems/EOS formulations that require compressibility factors -- not something generally applicable. It's also not used in any other places. Shall we remove this function until we are clear we really need it in the library?

2021-07-12 18:05 UTC, volpatto commented on Reaktoro/Thermodynamics/ThermodynamicsUtils.cpp
> +auto phaseCompressibilityFactors(const ChemicalProperties& properties) -> ChemicalVector
> It is a simple computation and also specific to systems/EOS formulations that require compressibility factors -- not something generally applicable.

Agreed. We can remove it, as we can easily calculate post-processing `Reaktoro`'s results. The `Z`-factor is important in PVT analysis and hydrocarbon systems, but it is simple to compute it with `Reaktoro::ChemicalProperties`. IMHO, we can remove it for now.

2021-07-12 18:09 UTC, volpatto commented on Reaktoro/Thermodynamics/ThermodynamicsUtils.cpp
> +auto phaseCompressibilityFactors(const ChemicalProperties& properties) -> ChemicalVector
Ah, one more thing: in general, the Z-factor is used to validate Cubic EoS results, since it is a key result for such EoSs. I don't remember if I added a test comparing Z results, but I did this study.

2021-07-12 18:13 UTC, volpatto commented on tests/regression/test_pedersen63.py
> +import numpy as np
Great, @alexandrebbruno! Thanks!

2021-07-12 18:15 UTC, volpatto commented on tests/regression/test_equilibrium_liq_gas_aq/test_equilibrium_CH4_H2S_CO2_H2O_liq_gas_aq_temperature_equal_310_95_K_and_62_6_bar_.csv
> +0,9.897014523419688e-23,0.011361212608224843,0.48236568923000694,1.0047813446754076e-22,9.897014523419688e-23,1.001374498416919e-22,9.4702520328251751e-23,0.050000000000000024,0.048877250212860657,0.
@alexandrebbruno do you still have the code that generates phase envelopes? If it is easy, can you generate one for this case? Don't worry, it can be after this PR.

2021-07-13 11:37 UTC, alexandrebbruno commented on Reaktoro/Thermodynamics/ThermodynamicsUtils.cpp
> +auto phaseCompressibilityFactors(const ChemicalProperties& properties) -> ChemicalVector
ok, it doesn't seem to be de right time to add this function. I will remove it.

- [ ] remove `phaseCompressibilityFactors`

2021-07-13 11:55 UTC, alexandrebbruno commented on Reaktoro/Thermodynamics/ThermodynamicsUtils.cpp
> +auto phaseCompressibilityFactors(const ChemicalProperties& properties) -> ChemicalVector
done

2021-07-13 11:57 UTC, alexandrebbruno commented on tests/regression/test_equilibrium_liq_gas_aq/test_equilibrium_CH4_H2S_CO2_H2O_liq_gas_aq_temperature_equal_310_95_K_and_62_6_bar_.csv
> +0,9.897014523419688e-23,0.011361212608224843,0.48236568923000694,1.0047813446754076e-22,9.897014523419688e-23,1.001374498416919e-22,9.4702520328251751e-23,0.050000000000000024,0.048877250212860657,0.
I don't have it now :/
But can try to compute the phase envelope of this case as soon as I have some free time, probably the next weekend

2021-07-14 13:59 UTC, allanleal approved these changes

2021-07-14 20:41 UTC, merged