Fix segmentation fault error in aqueous properties calculation and output
reaktoro/reaktoro pull request #217
Opened 2021-09-27 09:41 UTC by mtsveta

Fix segmentation fault error generated during the call

~~~c++
AqueousProps aqprops(props);
td::cout << aqprops << std::endl;
~~~

on the stage of pE calculation and during the output.

Tasks:

- [x] Fix segmentation fault error during the call `pE()`.
- [x] Fix segmentation fault error during the call of `<<operator()`.

2021-09-27 10:14 UTC, allanleal requested changes

2021-09-27 10:14 UTC, allanleal commented on Reaktoro/Thermodynamics/Aqueous/AqueousProps.cpp
> +        const auto E = system.phase(0).elements().size();
This presumes the aqueous phase is always the first phase in the system, which may not be the case.

2021-09-27 13:40 UTC, mtsveta commented on Reaktoro/Thermodynamics/Aqueous/AqueousProps.cpp
> +        const auto E = system.phase(0).elements().size();
Okay, I thought that it might be not too general. I have corrected this line.

2021-09-29 07:21 UTC, merged

2021-09-29 07:22 UTC, allanleal commented
Awesome, Svetlana!